### ISSUE TITLE
Publish android app to SkyDroid

### ISSUE THREAD

**Issue by redsolver** [jesusrp98/spacex-go#100]
[SkyDroid](https://skydroid.app) is a decentralized domain-based App Store for Android. 

An app is published on a domain name by adding a TXT record, for example `app.example.com`, and the user can then install the app by entering `app.example.com` in the SkyDroid app or by simply clicking a link (like in a web browser). So it's basically a direct APK download with the added convenience of auto-updates, rich metadata and more security. 

Publishing on SkyDroid is really fast and you only need a domain name and the [SkyDroid CLI](https://github.com/redsolver/skydroid-cli). Then just follow the instructions in the CLI Repo.

**Comment by Monik09** [comment]
@redsolver , I want to contribute to this. may I?

**Comment by jesusrp98** [comment]
Hey @Monik09 thanks for offering your help. I'd really like for this package to be offered in SkyDroid, but I don't have the knowledge nor the time to support that.

It would be awesome if you team up with @redsolver on it!
Let me know if you need anything.

**Comment by redsolver** [comment]
@jesusrp98 I added the needed metadata in #126, the only thing you need to do is to build a signed release APK and send it to me:
```
flutter build apk
```

**Comment by jesusrp98** [comment]
> @jesusrp98 I added the needed metadata in #126, the only thing you need to do is to build a signed release APK and send it to me:
> 
> ```
> flutter build apk
> ```

Thanks for the job!
I have a couple questions here:
- Should I send you an APK, or an Android App Bundle (AAB) that combines 32 & 64bits binaries into one?
- I think there should be a better way to do this, maybe using GitHub Actions? I'd like to deploy to SkyDroid directly via some CD tools.

**Comment by redsolver** [comment]
You can split the APKs by ABI and send me all the generated APK files to make the download size for users smaller (like with App Bundles): `flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi` (This will generate 3 APK files)

---

imo using the SkyDroid CLI (https://skydroid.dev) to publish is easier than with GitHub actions, because you don't need to set up a full Flutter build environment and give your personal app signing keys to GitHub.

If you want to publish it yourself using the CLI: After merging the metadata file, you can simply install the SkyDroid CLI with `flutter pub global activate skydroid_cli` and then execute `flutter build apk` and `skydroid publish` to publish it directly. (You would need your own domain name for this)
^ You can of course automate this process with GitHub actions

**Comment by m0veax** [comment]
+1 for using Github Actions with skyhub_cli

**Comment by jesusrp98** [comment]
Ok we can do it manually at this moment, and I will implement the automatic apk upload at a later time. 

Could you please tell me your email for me to pass you the apk?

**Comment by redsolver** [comment]
@jesusrp98 info@redsolver.net

**Comment by jesusrp98** [comment]
@redsolver Already sent it (sorry for the delay, busy day).

@Monik09 If you want to still contribute to this project you could take a look at how to deploy the APK directly from GitHub Actions!

**Comment by redsolver** [comment]
@jesusrp98 Do you have a domain name or should I publish it under a custom one?

**Comment by jesusrp98** [comment]
The app's domain is `com.chechu.cherry`, you could use that, if that's what are you reffering to.

Currently I don't have any personal internet domain bought tho.

**Comment by redsolver** [comment]
Ok, I just published it under a custom subdomain: https://to.skydroid.app/spacex-go.bridgedroid

**Comment by jesusrp98** [comment]
Thank you very much for the work here @redsolver!

Since this has already been done, I'm Closing the issue, but mention me if you need anything else :)
