### ISSUE TITLE
Picture settings resolution

### ISSUE THREAD

**Issue by Bohne13** [jesusrp98/spacex-go#113]
## Environment 
v.2.12.0
Android 10 

Oneplus 7T with official open beta android

Pictures are shown if picture quality is set to medium or low, but at high quality I can't see any of the pictures!

Thanks for this great beautiful app, by the way!

**Comment by jesusrp98** [comment]
Hey! Thanks for identifying this bug.

It has been fixed on https://github.com/jesusrp98/spacex-go/pull/114.

Uploading it to the Play Store itm!
