### ISSUE TITLE
Livestream on YouTube

### ISSUE THREAD

**Issue by Bohne13** [jesusrp98/spacex-go#115]
## Environment

App: 2.12.0
Android: Android 10 security patch level Oktober 19
Device: OnePlus 7t

Open the Livestreams from YouTube directly in the YouTube Android App instead of the in-app browser window!

Thanks, would be nice!

**Comment by jesusrp98** [comment]
Hey @Bohne13 
Thanks to the continuous support for the SpaceX GO! app!

I'd like to get more information about the question you've asked, because I don't really get what you're saying.

Could you explain it a bit further please?

**Comment by Bohne13** [comment]
Hey @jesusrp98 

In your app on the home tab, it is possible to tap on "watch live" as soon as the livestream of the launch is available!?!

At the actual app version, when I tab on "watch live" it opens a browser window with YouTube.

It would by better if it's launching directly on the YouTube app (when it's installed on your phone)

**Comment by Bohne13** [comment]
And sorry,
I accidentally closed this issue and can't finde the option to undo this 😲

**Comment by jesusrp98** [comment]
Yes, when the livestream is available from SpaceX the Home tab would let you click the 'Watch live' to go to YouTube.

Unfortunately, I can't control if the app opens the YT app directly or rather the web browser.

**Comment by m0veax** [comment]
But the users can set the default app for youtube links in their android
settings. Just added if someone finds that issue per search engine :)

Jesús Rodríguez <notifications@github.com> schrieb am Sa., 9. Jan. 2021,
18:32:

**Comment by Bohne13** [comment]
@m0veax 

yeah, that's wright I checked this before i wrote this issue. So now I checked it again and I did made a screenshot

![Screenshot_20210109-214729](https://user-images.githubusercontent.com/20006695/104108440-fefd1a80-52c4-11eb-886f-ab5b6d929b91.jpg)


There are all the supported Youtube links listed. Could be a unsupported Youtube link why it's not working.

**Comment by m0veax** [comment]
Do you have the possibility to debug the given URL?

Maybe we could continue from there?

If I find some time I will try to look that up next week

Jonas Haberkorn <notifications@github.com> schrieb am Sa., 9. Jan. 2021,
21:54:

**Comment by jesusrp98** [comment]
This is the link for the latest SpaceX launch, Turksat 5A: https://youtu.be/9I0UYXVqIn8.

Are you able to launch the YT app from the launch page, clicking in the play button?

**Comment by Bohne13** [comment]
@m0veax I checked this and what I did find out, it's a problem with the in-app-browser! So first of all the Android system is launching a Link in the in-app-browser (and I can't find some settings to deactivate the in-app-browser system wide).
When I go to "settings" in the in-app-browser and tab on "Open in Chrome" than it's switching automatically to the youtube app.

@jesusrp98 I tried that link and it works, it opens directly in the Youtube app. So over all I think it's a problem with the in-app-browser.

The only solution could be to restrict the app from using the in-app-browser option. There is a link below for better understanding, what I mean.

[Informations about in-app browser](https://gadgetstouse.com/blog/2019/12/21/how-to-disable-in-app-browser-for-android-apps/#:~:text=Open%20the%20Google%20app%20on,the%20toggle%20to%20disable%20it.)

**Comment by jesusrp98** [comment]
At this moment, this app opens URLs using a Flutter package that features in-app browsing. This is pretty handly, and improves UX in my opinion.

What you could do is trying to open the current YT in-app window using a native app. For example, the latest Firefox version allows you to do exactly that, with a handy 'Open in app' button.

I'm planning to rewrite how the app handles URLs in the future, but right now I have other priorities in mind:
- Improve the notification system reliability, because it has been a pain in the over the last few months.
- Add Dragon crew support. Full crew support was added a couple versions ago, but I have to implement the UI.
- Rewrite how the app handles info internally (allowing for data caching :)

I think I'm going to be occupied for the next few months so :)

**Comment by Bohne13** [comment]
Sounds like you have a fully loaded todo-list for 2021!

Thanks for the information about url-handling etc.
I will stay with Chrome and will be excited to see all the changes you have planed!
So you can close this conversation or let it open wit low priority ;)

**Comment by m0veax** [comment]
Do you have a plan about the URL handling?

Maybe I can help out :)

Jonas Haberkorn <notifications@github.com> schrieb am Mo., 11. Jan. 2021,
20:04:

**Comment by jesusrp98** [comment]
I don't have a plan at this moment, just a couple ideas:
- Launching links in in-app browser should be the default, this is not going to change.
- Maybe implementing a setting that allows the user to open links using default system browser (but I need to investigate how to do this in Flutter).

**Comment by m0veax** [comment]
If implementing a setting is okay for you, please assign me this issue.

This week I can't investigate, but I would like to get this done in
February :)

Jesús Rodríguez <notifications@github.com> schrieb am Di., 12. Jan. 2021,
11:17:

**Comment by jesusrp98** [comment]
No problem @m0veax. I'm closing this issue in favor of opening a new one detailing everything related to this new feature :)
