### ISSUE TITLE
Payload capsule could be null. Use null-aware operator to access its properties

### ISSUE THREAD

**Issue by giohappy** [jesusrp98/spacex-go#140]
## Environment

**App version:**  master
**Android version:**  API29  
**Device information:**  Emulator

## Description
The home tab crashes if payload.capsule is null [here](https://github.com/jesusrp98/spacex-go/blob/master/lib/ui/views/tabs/home.dart#L436).

Adding a null-aware access to the payload's capsule property fix the problem:

`payload.capsule?.serial == null`

## Images
Without null-aware access:
![image](https://user-images.githubusercontent.com/571129/130224296-8d3dcc5d-42ac-400a-8413-fbe231878b35.png)

With null-aware access:
![image](https://user-images.githubusercontent.com/571129/130224354-203f930f-199a-4155-951f-cb211f4b1ba3.png)

**Comment by jesusrp98** [comment]
Hey! Thank you very much for opening an issue related to this problem.
Unfortunately I've had zero time for this project lately :/

Could you please open a PR containing the fixes for this issue?
I'd more than happily merge them to `master` :)
