### ISSUE TITLE
Having errors running the SpaceX Go App using SpaceX API v3, only working with v4. how can i make it work with v3

### ISSUE THREAD

**Issue by patelmohammed357** [jesusrp98/spacex-go#142]
Having errors running the SpaceX Go App using SpaceX API v3, only working with v4. how can i make it work with v3?

**Comment by iNoles** [comment]
Well, V3 going to be deprecated soon.

https://github.com/r-spacex/SpaceX-API/issues/380

**Comment by jesusrp98** [comment]
Indeed, v3 of the API is going to be deprecated.

Consider using v4 or v5 of the API from now on.
