### ISSUE TITLE
Change in youtube button on "latest" tab

### ISSUE THREAD

**Issue by thechawla225** [jesusrp98/spacex-go#143]
## Environment

**App version:  2.14.0**    
**Android version: 9**    
**Device information: Oppo Realme 1**    

## Description

In the 'Latest' tab, on touching on one of the launches there comes this button in yellow that leads to youtube link and opens brower:

![screenshot](https://user-images.githubusercontent.com/45570514/132173679-f7dcc17f-8073-4d43-806f-42105ada2644.jpg)

I suggest that this button open youtube app directly (if installed on device) instead of opening a browser window with the link to the video.
 
<a href = 'https://pub.dev/packages/url_launcher'> Url Launcher</a> Should be used but it should open the app instead of a browser window

**Comment by jesusrp98** [comment]
Hey @thechawla225!
Try navigating to 'Settings' and select 'System browser' as the 'Default browser'.

This way, you'd be using `url_launcher` to open URLs.
Hope this solves your issue :)

**Comment by thechawla225** [comment]
Thanks a lot @jesusrp98 I'll try that.
