### ISSUE TITLE
Vehicles tab 

### ISSUE THREAD

**Issue by vipul1298** [jesusrp98/spacex-go#144]
## Environment

**App version:**  2.14.0 
**Android version:** 9  
**Device information:**  Redmi note 5 pro

## Description

**Expected behavior:** In working state

**Current behavior:** Showing as in below image given 

## Images   
![Screenshot_2021-09-06-15-26-32-443_com chechu cherry](https://user-images.githubusercontent.com/37983968/132200738-70442216-60a7-4f0a-bbda-71ca4dbb8b99.jpg)

## Stacktrace/Logcat   

Showing something like this in debug console :
I/flutter (27051): onChange: VehiclesCubit, Change { currentState: (RequestStatus.error: null, NoSuchMethodError: The method '%' was called on null.
I/flutter (27051): Receiver: null
I/flutter (27051): Tried calling: %(4)), nextState: (RequestStatus.loading: null, null) }

**Comment by jesusrp98** [comment]
This is an issue with the SpaceX API.

You can see more details here https://github.com/r-spacex/SpaceX-API/issues/910.
