### ISSUE TITLE
Review UI/UX

### ISSUE THREAD

**Issue by deandreamatias** [jesusrp98/spacex-go#29]
Hi people.
My name is Matias and I am an aspiring Designer UI / UX, with some project like [this](https://www.behance.net/gallery/77595511/Technological-Support-Mobile-App-UI-UX).
I wanted to compile here some suggestions on the part of UI and UX of the application, which I liked for being in Flutter (which I am studying) and open source <3.
I would like to discuss them and in case I accept some or all of the suggestions, I can open separate issues for each one and find a solution together. Follow the thread.

Setup:
- Android 8.0
- Huawei P10 Lite
- Language: Spanish
- Dark mode (no black)
- Branch Master

0. General:
0.1. ListItem sometimes have many different elements and information (ex Info and Home). All this can overload the user.
0.2. The bottom tab in the dark mode does not contrast well with the background of the app.
0.3. (Opinion) I liked (a lot) the images of the top bar, but I do not know until I put this slide does not disperse the user's attention of what would be 'important'.
0.4 The images in the topBar with light colors do not make the title of the page (contrast) legible.
0.5 Once browsing through the tabs, I find a bug. For example, I go from home to vehicles, I return to home and show on the screen the final part of the list and not the start.
1. Loading page
1.1 An animation with the rocket can make the wait more dynamic and fun.
2. Home page
2.1. The page in is not very clear to what it refers, it does not have a clear title or indication of what it would be. After a while, it can be deduced that the page refers to the launch of the next space vehicle.
2.2 Sometimes the buttons may not have an available onTap, but the user will try to click in the same way, since the item has the appearance of a button and/or is used to clicking there.
3. Info page
3.1. About SpaceX Go !. The link is a giphy. I think it should be something temporary until the feature is ready.
3.2. Imperial units? In Spanish, this string is cut because it does not fit in the ListItem.
4. Upcoming and latest
4.1. As you said in [this article](https://medium.com/@jesusillorp98/designing-the-ultimate-spacex-app-2d48b2fce216), include a filter by the characteristics of the releases, it would be ideal.
5. Company
5.1 The description of the company is 'loose' below the number of employees. There is no indication of what this paragraph would be.
5.2 The dollar sign is always placed before the amount in money that you want to express.
5.3 In Spanish, the word 'operations director' is cut off.
5.4 The list of facts/history does not have a title either. They put a lot of items without knowing clearly what they are.
6. Vehicle details
6.1 The button that takes to see the launch video, has the icon 'play'. It gives the impression of starting something on the screen itself. But it actually shows a video on another platform (usually).
6.2 In some cards that the text extrapolates the size of the card, an arrow is placed downwards. When this arrow is clicked and the card expanded, it disappears and the card cannot be closed anymore. If the user opens the card unintentionally or wants to close it, he does not have that option.
6.3 In Spanish, some strings are cut by not entering the card. EX: Date of ..., vehicle of ... and distance to ...
7. Launch details
7.1 The gray icon with a stroke does not indicate exactly what the state is unknown. A question symbol inside the gray, I think would be ideal.
8. Accessibility.
8.1 Increasing the font size x1.5 some strings exceed the limits set for them. Already x2.0, many strings do it.

Conclusion:
The design of the application seems excellent. He has a good identity. The animations are quite dynamic, but some micro interactions could be added.
In general, the fluency of the app is good, but there are some elements that are not well known for what they are, missing a descriptive label.
I also think it's great that the app is in several languages since it has been born recently.
I see great potential in this app to reach all those passionate about Space and SpaceX launches.

**Comment by jesusrp98** [comment]
Such a great review!
There's a lot of changes that could be implemented to improve the UX/UI. Going to write a list with all changes that could be implemented in the v2.4 update, scheduled for May.

Going to post that list here once I have the definitive one.

**Comment by jesusrp98** [comment]
With the help of @deandreamatias, there have been lots of UI/UX tweaks implemented in the v2.4 update.
Go to issue #30 if you want to check which specific changed have been made.


Thanks once again to @deandreamatias to take the time to write this UI review, and for continuously helping me develop this project!
