### ISSUE TITLE
Substancial UI/UX improvements

### ISSUE THREAD

**Issue by jesusrp98** [jesusrp98/spacex-go#30]
Update specific UI elements, to improve the overall user experience. This issue is inspired by #29 and will be completed in conjunction with @deandreamatias.

- [x] Update 'Settings' & 'About' screen, separating all list elements into categories.
- [x] Improve contrast between navigation bar & background when dark mode is on.
- [x] Improve 'top bar' and title legibility.
- [x] Improve the Home screen, to better indicate what is displayed.
- [x] Improve Home screen's list tiles, to better indicate which items can be clicked.
- [x] Update strings that are cut in half.
- [x] Improve Company screen legibility.
- [x] Update 'Watch replay' icon, inside a launch's screen and roadster screen.
- [x] Add the ability to 'minimize' a `ExpandWidget`.
- [x] Update `RowItem`'s icons & colors.
- [x] Reduce text size (everything seems big).
- [x] Tweak themes' colors (especially the clear theme's accent color).
- [x] Improve `HeaderMap`, adding the ability to change colors based on the theme.
- [x] Reduce padding between cards.
- [x] Add PopupMenus to all tabs.
- [x] Update static SpaceX photos all around the app.

This issue can be modified in the future, to include new UI improvements.
Write a comment with your own ideas & opinions!

**Comment by deandreamatias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Massive UI/UX update](https://trello.com/c/I5hEwyOj/1-massive-ui-ux-update)
