### ISSUE TITLE
Implement RowItem & Separator as a dependency

### ISSUE THREAD

**Issue by jesusrp98** [jesusrp98/spacex-go#33]
Create public Dart plugins, upload them to the [Dart Packages](https://pub.dartlang.org/) website.
This means that both widgets will have to be more customizable.
After that, add the package as a dependency inside the `pubspec.yaml` file.

**Comment by deandreamatias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add RowItem & Separator as a dependency](https://trello.com/c/HznxfLUv/2-add-rowitem-as-a-dependency)
