### ISSUE TITLE
Implement ExpandWidget as a dependency

### ISSUE THREAD

**Issue by jesusrp98** [jesusrp98/spacex-go#34]
Create public Dart plugins, upload them to the [Dart Packages](https://pub.dartlang.org/) website.
This means that the widget will have to be more customizable.
After that, add the package as a dependency inside the pubspec.yaml file.

**Comment by deandreamatias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add ExpandWidget as dependency](https://trello.com/c/VPnjJzSm/3-add-expandwidget-as-dependency)

**Comment by jesusrp98** [comment]
This has been achieved by creating the [`expand_widget`](https://pub.dev/packages/expand_widget) package, with built-in animation.
