### ISSUE TITLE
Latest tab crash on refresh and scroll down without internet

### ISSUE THREAD

**Issue by mneira10** [jesusrp98/spacex-go#39]
## Environment

**App version:**    

2.3.1

**Android version:**    

Android 9 - API 28

**Device information:**    

Xiaomi Mi 8 Lite

## Description

**Current behaviour:** 
When there is no data (or the user turns off wifi and mobile data), refreshes the latest tab and scrolls down, the app displays a red screen with a range error.

Related to #10 

**Expected behaviour:** 

The app should not display errors if there is no data and the latest page is refreshed. 

## Steps to reproduce

1. Start app
2. Navigate to latest
3. Turn off all data - wifi and mobile data
4. Reload page 
5. Scroll down 

## Video   

[![Bug](https://user-images.githubusercontent.com/30906976/57543830-18450b00-731b-11e9-85ad-d87956ccb2da.png)](https://www.youtube.com/watch?v=1G1Z_AzdoNo&feature=youtu.be)

**Comment by jesusrp98** [comment]
Planning to add connection awareness, for both loading & reloading methods in the near future. What you've implemented in the pull request is a pretty good start.

Like the image quality settings, this will be implemented in the v2.5 update. You can continue tinkering with this feature in #38 if you want to :)

Thank you very much!

**Comment by jesusrp98** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Connection awareness](https://trello.com/c/vk9T1y5G/5-connection-awareness)

**Comment by jesusrp98** [comment]
Changes made to control network status are now pulled to the `dev` branch.
* Every time the user pulls to refresh the screen, it checks if there's internet available. If not, information will be kept at display, and then warns the user that there isn't an internet connection available to download data from.
* Also, if the app starts and it checks that there's no internet, it will show a custom screen, like [this one](https://user-images.githubusercontent.com/8961959/58487685-5427ff00-8168-11e9-99b2-58013ba079f7.jpg).

This function inside the `QueryModel` is the one responsible for checking internet connection.
```
  // Checks internet connection & sets [_status] variable
  Future<bool> connectionFailure() async {
    _status =
        await Connectivity().checkConnectivity() == ConnectivityResult.none
            ? Status.error
            : Status.loading;
    return !isLoading;
  }
```

Once again, thanks for taking the time to help in the development of this app :)
