### ISSUE TITLE
[Feature request] Launch notifications

### ISSUE THREAD

**Issue by siphomateke** [jesusrp98/spacex-go#4]
Could you add a feature to send a notification before a launch takes place? I like to watch the livestreams but often forget when they are.

**Comment by jesusrp98** [comment]
I'm currently developing a whole new SpaceX app in the [space-curiosity](https://github.com/jesusrp98/space-curiosity) repository. Once I finished it, I'm going to push all changes (basically the entire SpaceX module) to this repo. I'd like to start integrating it into here in about a week.

One of the features I've added is 'Add to calendar' support. Using [this package](https://pub.dartlang.org/packages/add_2_calendar), you'll be able to add a specific launch to your favourite calendar app.

At this moment, I haven't manage to implement a full notification system, but I think this would be a nice addition to the app experience :)

Thanks for your feedback!

**Comment by jesusrp98** [comment]
I've already merge the `v2` branch to `master`, which means that all changes are now available to everyone!

As I said, the 'Add to calendar' feature is fully implemented and working.

Unfortunately, I'm not able, at this moment, to implement a fully functional dynamic notifications system, but if in the future I manage to integrate it, I'll reopen this issue.

Thanks, and enjoy the v2.0 update! :)
