### ISSUE TITLE
The link in About SpaceX Go! is a giphy

### ISSUE THREAD

**Issue by deandreamatias** [jesusrp98/spacex-go#41]
## Environment

**App version:**  2.4.0
**Android version:**  8.0
**Device information:**  Huawei P10 Lite

## Description

**Expected behavior:** 
When press in About SpaceX Go!, open a release details.

**Current behavior:** 
When press in About SpaceX Go!, open a giphy.

## Steps to reproduce

1. Open menu and select about
2. Press in About SpaceX Go!
3. Look a giphy

**Comment by deandreamatias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a release details](https://trello.com/c/1bButwjy/14-create-a-release-details)

**Comment by jesusrp98** [comment]
One alternative to the Elon Musk easter egg would be a complete changelog from the app.

**Comment by jesusrp98** [comment]
> One alternative to the Elon Musk easter egg would be a complete changelog from the app.


This feature has been now added. The changelog can be find [here](https://github.com/jesusrp98/spacex-go/blob/dev/CHANGELOG.md).

Here is a photo of how it looks like:

![Screenshot_20190609-123444](https://user-images.githubusercontent.com/8961959/59158052-d42d5d80-8ab4-11e9-917b-fd972afa18af.jpg)
