### ISSUE TITLE
Apply boutton

### ISSUE THREAD

**Issue by skemayou** [jesusrp98/spacex-go#63]
Hi Jesusrp98
Thanks for your great job.
I am new with flutter and i am trying to consume my restful service here http://pambe-jobs.com/apex/a182480/jobs/positions
the json format is not the same as the one you r using. 
can you please help me how can i make it works

Thanks

**Comment by jesusrp98** [comment]
Hey @skemayou thanks for asking.

This page is used only to post issues related to the SpaceX GO! project.
You can write to my [personal email](mailto:jesusrope98@outlook.com) for further Flutter-related questions.

Hope you understand :)
