### ISSUE TITLE
added an easter egg for this app?

### ISSUE THREAD

**Issue by ButterflyTech** [jesusrp98/spacex-go#67]
## Environment

**App version:**    
2.8
**Android version:**    
Andriod 10
**Device information:**    
XiaoMi Transparent 9

## Description
I have a crazy idea, I want to add an egg to this app, a game egg: a rocket simulator game egg like Spaceflight Simulator

**What you'd like to happen:** 

a rocket simulator game egg like Spaceflight Simulator

**Images:**   
![image](https://user-images.githubusercontent.com/50225144/66882311-80032e80-effc-11e9-9a7e-6532dc8a97b5.png)

**Comment by jesusrp98** [comment]
Are you planning about adding a whole game to this app??

How it could be? I mean, it'd increase the size of the app considerably.
One option would be app a link to its Store page or something, adding a whole game would be overkill.

**Comment by zinwalin** [comment]
> Are you planning about adding a whole game to this app??
> 
> How it could be? I mean, it'd increase the size of the app considerably.
> One option would be app a link to its Store page or something, adding a whole game would be overkill.

it's better to focus features with flutter.  I'm interested in push notification, local or remote.

**Comment by jesusrp98** [comment]
Yeah, me too! I'm also really interested on adding cool & new features.
For instance, local notifications were introduced a couple versions earlier.
Features like improved search, 'add to calendar'...

If you have suggestions about new & interesting features, let me know @zinwalin @ButterflyTech !

**Comment by ButterflyTech** [comment]
> Are you planning about adding a whole game to this app??
> 
> How it could be? I mean, it'd increase the size of the app considerably.
> One option would be app a link to its Store page or something, adding a whole game would be overkill.

emmm, maybe a mini version will have a mini size, only included Spacex rockets, Earth and Mars, I will try to build an alpha version to see the package size, later, we will decide whether to add this egg, how?

**Comment by ButterflyTech** [comment]
> > Are you planning about adding a whole game to this app??
> > How it could be? I mean, it'd increase the size of the app considerably.
> > One option would be app a link to its Store page or something, adding a whole game would be overkill.
> 
> it's better to focus features with flutter. I'm interested in push notification, local or remote.

how about [firebase fcm ](https://firebase.google.com/docs/cloud-messaging)to implement the remote notification feature?
