### ISSUE TITLE
Adding a launch to the calendar fails on iOS

### ISSUE THREAD

**Issue by bkbonner** [jesusrp98/spacex-go#7]
I received the error:

Could not cast value of type 'NSNull' (0x10909e8c8) to 'NSString' (0x1086a4c40).

It was blowing up when I tried to add an event to the iOS calendar that didn't have a description coming back from the data.

I was able to get things added to the calendar, but only after I added a null safe check to:
`description: model.launch.details??""`, in tab_home.dart
and
`description: _launch.details??""`, in page_launch.dart

**Comment by jesusrp98** [comment]
This issue should now be resolved, thanks to your pull request and subsequents commits.
Thank you very much for your help & support :)
