### ISSUE TITLE
Bug when you start the app, loading screen doesn't change

### ISSUE THREAD

**Issue by AfLosada** [jesusrp98/spacex-go#72]
## Environment

**App version:**  2.7
**Android version:**  9
**Device information:**  ASUS_X017DA
## Description

**Expected behavior:** 
When the app cold starts, it should update the home page when it downloads all API images.

**Current behavior:** 
When the app cold starts, it stays forever in the loading screen until you interact with, it works if you click on some other tab. 

## Steps to reproduce

1. Cold start the app (Delete it from your phone and run it with -profile mode in flutter debug mode)
2. Wait until the app loads
3. It should stay forever in the loading symbol

## Images 

![bug](https://user-images.githubusercontent.com/31115265/69304683-81bda480-0bef-11ea-80df-a9550190ca3d.jpeg)

## Fix

I believe I have fixed the issue, but I wanted to follow the community guidelines to contribute in this repository.

**Comment by jesusrp98** [comment]
This issue has been around for a couple versions now. It's related to how data is load using `QueryModel` and the `provider` package.

At this moment, I don't know how to fix it. If anyone thinks how to solve this issue, please let me know :)

**Comment by jesusrp98** [comment]
This appears to be now fixed, using the latest version of the `provider` package.

Let me know if it reappears :)
