### ISSUE TITLE
getting packages fails

### ISSUE THREAD

**Issue by mbravorus** [jesusrp98/spacex-go#76]
in a freshly cloned repo, running `flutter packages get` produces error:

```
$ flutter packages get
Because flutter_i18n >=0.0.2 depends on flutter_localizations any from sdk which depends on intl 0.16.0, flutter_i18n >=0.0.2 requires intl 0.16.0.
So, because cherry depends on both flutter_i18n ^0.8.2 and intl 0.15.8, version solving failed.
Running "flutter pub get" in spacex-go...                               
pub get failed (1; So, because cherry depends on both flutter_i18n ^0.8.2 and intl 0.15.8, version solving failed.)
```

**Comment by jesusrp98** [comment]
This error was produced when I updated the package to support Flutter v1.12. There were a couple packages that weren't happy about that.

Luckily, all of them have been updated: the project should be able to build now.
Let me know if you have further issues :)
