### ISSUE TITLE
iOS issue: Conditional cast from 'AppDelegate' to 'UNUserNotificationCenterDelegate' always succeeds

### ISSUE THREAD

**Issue by zinwalin** [jesusrp98/spacex-go#89]
![image](https://user-images.githubusercontent.com/5416196/85244323-dae80200-b476-11ea-901a-ea8beb3580f7.png)

**Comment by jesusrp98** [comment]
Hey! I'll update the app to the iOS platform, and will check this issue.

Thanks for the report! :)

**Comment by jesusrp98** [comment]
Haven't had any problems building the app for iOS. Is this still an issue @zinwalin ?
