### ISSUE TITLE
Permission denied (publickey) git@github.com:jesusrp98/cherry_components.git

### ISSUE THREAD

**Issue by haikuowuya** [jesusrp98/spacex-go#94]
Git error. Command: `git fetch`
stdout: 
stderr: git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jesusrp98** [comment]
Yeah sorry. I'm using a custom ui toolkit for all my apps called 'cherry' and until now it was private!
Right now it's WIP, but it will be cleaned and publish in pub.dev in the coming days/weeks.

The package is public now, so it should be fixed!
