### ISSUE TITLE
Upcoming launches list opens an incorrect launch page

### ISSUE THREAD

**Issue by Dexalt142** [jesusrp98/spacex-go#99]
## Environment

**App version:** 2.10.1
**Android version:** 9
**Device information:**  Xiaomi Redmi Note 5 Pro

## Description

**Expected behavior:** When clicking the list item, it should open the corresponding launch page.

**Current behavior:** Clicking the second item will open the first item page and so on except for the last one. Clicking the last item will open a blank page. 

## Steps to reproduce

1. Open the upcoming tab
2. Click one of the items on the list.
3. Then it should open an incorrect page

**Comment by jesusrp98** [comment]
I know this issue very well. It is related to the API, that doesn't return correct data sometime, specially regarding flight numbers.

The app tells that screen to show launch details related to a specific flight number. If there are two flights with the same number, the system can be confused.

I hope this issue doesn't pop up in the future. I'm in the process of integrating all the features of the v4 of the SpaceX API in this app, and it should iron out this issue.
